# Generated by Django 6.0.3 on 2026-03-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ministerio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('subtitulo', models.CharField(blank=True, max_length=200)),
                ('resumo', models.CharField(max_length=300)),
                ('descricao', models.TextField()),
                ('lider', models.CharField(max_length=120)),
                ('cargo_lider', models.CharField(blank=True, max_length=120)),
                ('local', models.CharField(max_length=200)),
                ('dia_reuniao', models.CharField(blank=True, max_length=100)),
                ('horario', models.CharField(blank=True, max_length=100)),
                ('contato', models.CharField(blank=True, max_length=50)),
                ('versiculo', models.CharField(blank=True, max_length=255)),
                ('imagem_capa', models.ImageField(upload_to='ministerios/capas/')),
                ('imagem_principal', models.ImageField(upload_to='ministerios/principais/')),
                ('ativo', models.BooleanField(default=True)),
                ('destaque', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ministério',
                'verbose_name_plural': 'Ministérios',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
