# Generated by Django 6.0.3 on 2026-03-17 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ministerio',
            name='dia_reuniao',
        ),
        migrations.RemoveField(
            model_name='ministerio',
            name='horario',
        ),
        migrations.CreateModel(
            name='Culto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ministerio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultos', to='core.ministerio')),
            ],
            options={
                'verbose_name': 'Culto',
                'verbose_name_plural': 'Cultos',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='departamentos/')),
                ('lider', models.CharField(blank=True, max_length=120)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ministerio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='core.ministerio')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
