# Generated by Django 6.0.3 on 2026-03-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_ministerio_dia_reuniao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='lider',
        ),
        migrations.RemoveField(
            model_name='ministerio',
            name='cargo_lider',
        ),
        migrations.RemoveField(
            model_name='ministerio',
            name='lider',
        ),
        migrations.AddField(
            model_name='departamento',
            name='foto_lideranca',
            field=models.ImageField(blank=True, null=True, upload_to='departamentos/lideranca/'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='lider_nome',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='lider_nome_esposa',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='ministerio',
            name='foto_casal_lideranca',
            field=models.ImageField(blank=True, null=True, upload_to='ministerios/lideranca/'),
        ),
        migrations.AddField(
            model_name='ministerio',
            name='pastor_nome',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='ministerio',
            name='pastora_nome',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='departamentos/'),
        ),
        migrations.AlterField(
            model_name='ministerio',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ministerio',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='ministerios/capas/'),
        ),
        migrations.AlterField(
            model_name='ministerio',
            name='imagem_principal',
            field=models.ImageField(blank=True, null=True, upload_to='ministerios/principais/'),
        ),
        migrations.AlterField(
            model_name='ministerio',
            name='local',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ministerio',
            name='resumo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
