# Generated by Django 6.0.3 on 2026-03-19 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_departamento_lider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('local', 'Evento da igreja'), ('geral', 'Evento geral')], default='local', max_length=10)),
                ('data', models.DateField()),
                ('horario', models.CharField(blank=True, max_length=50, null=True)),
                ('local', models.CharField(blank=True, max_length=200, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('ativo', models.BooleanField(default=True)),
                ('destaque', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ministerio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.ministerio')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data', 'titulo'],
            },
        ),
    ]
