# Generated by Django 6.0.3 on 2026-03-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_perfilacesso_registroauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='gratuito',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='publico',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('infantil', 'Infantil'), ('outros', 'Outros')], default='outros', max_length=20),
        ),
    ]
